app:
  name: Thankee (default)

mongo:
  thankee:
    url: mongodb://thankee:thankee@192.168.50.4:27017/thankee?poolSize=20

rabbit:
  thankee:
    config:
      url: amqp://thankee:thankee@192.168.50.3:5672/thankee
      reconnectTimeout: 1000
    exchange:
      transfer: transfer
